# Generated by Django 5.2.13 on 2026-04-23 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0005_topic_flashcardset_flashcard_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='is_public',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='flashcardset',
            name='is_public',
            field=models.BooleanField(default=True),
        ),
    ]
