# Generated by Django 5.2.13 on 2026-04-23 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0006_article_is_public_flashcardset_is_public'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
